[package]
name = "lyceumnstubot"
version = "2.0.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
reqwest = "0.12"
anyhow = "1.0"
